[build]
  command = "npm run build"
  publish = "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/forms"
  status = 200
  force = true
